# Generated by Django 4.1.3 on 2022-11-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlists',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
