# Generated by Django 4.1.3 on 2022-11-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_rename_user_id_playlists_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jams.artist')),
            ],
        ),
    ]
