# Generated by Django 4.1.3 on 2022-11-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0006_alter_album_name_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jams.artist'),
        ),
        migrations.AlterField(
            model_name='playlists',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jams.users'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jams.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jams.artist'),
        ),
    ]
